### PR TITLE
153 Autocomplete component

### LINKED ISSUE #153: Implement member autocomplete component
## Description
Implement an autocomplete component that allows users to search a keyword and select a corresponding value from a list of asynchronously loaded options. Once the generic component is complete, create a wrapper around it that allows users to search for titan members.

These components will be used in the organization role management UI.

### PR DESCRIPTION
**Pull request by MichaelJamesParsons**
Resolves #153 

This PR contains only the component. It has been tested on another unstable/incomplete branch.

titan_autocomplete

    ```
    git rebase -i $(git merge-base HEAD master)
    git push origin NAME_OF_BRANCH --force-with-lease
    ```

### CODE REVIEW

**Comment by MichaelJamesParsons** [comment]
@ELD ping

**Comment by MichaelJamesParsons** [comment]
@ELD ping

**Comment by ELD** [comment]
@MichaelJamesParsons Is this being used anywhere or is this just the component?

**Comment by MichaelJamesParsons** [comment]
@ELD The linked issue explains the purpose of this component (#153). In short, it will be used by the organization role management UI to assign users to a specific role.

**Comment by MichaelJamesParsons** [comment]
@ELD ping. This PR has been pending review for almost one month.

**Comment by ELD** [comment]
@MichaelJamesParsons I think this PR adds solid component, but since it's not being consumed or displayed to the end user, I think this work should remain on the branch for the greater organization management work. I'm not seeing a compelling case to merge it now as opposed to later with the full organization management UI work.

**Comment by MichaelJamesParsons** [comment]
@ELD I've got another WIP branch for building out the organization role management UI, which uses this component. The branch has been divided into many smaller PRs for faster reviews and a clearer commit history.

Considering we do not have multiple developers contributing features in parallel, your recommendation adds unnecessary process to this repo. Numerous other PRs related to org role management have been merged without concern. I'm surprised this is being addressed now.

**Comment by ELD** [comment]
@MichaelJamesParsons Let's keep this component part of #108 since that's the only place I can test the component. Merging that PR will constitute merging the component.

**Pull request closed without merging**
