### PR TITLE
Apply clippy lint suggestions

### PR DESCRIPTION
**Pull request by ELD**
This applies several lint fixes from running `cargo clippy`. Most lint fixes revolve around unnecessary returns or ways to rewrite expressions that end up unwrapping a value.

### CODE REVIEW

**Comment by MichaelJamesParsons** [comment]
@ELD Please rebase this branch with master

**Comment by ELD** [comment]
@MichaelJamesParsons Done. The only linter suggestion I didn't take was the one about a nested module with the same name as the outer module (the `organizations` module inside of the `organizations` module, https://rust-lang.github.io/rust-clippy/master/#module_inception). I didn't want to make a unilateral decision on renaming the module, but we should strongly consider it.

**Comment by MichaelJamesParsons** [comment]
@ELD The name collision there is a coincidence. `organizations.rs` refers to the `organization` entity, not the module. We can rename the directory (`teams`?), but the rs file should remain the same.

**Comment by ELD** [comment]
@MichaelJamesParsons Sounds good. I refactored the outer module name to `teams`.

**Pull request merged**
