### PR TITLE
94 create report

### PR DESCRIPTION
**Pull request by MichaelJamesParsons**
> **Pending** #93 to be merged before squashing this PR.

Resolves #96 

### Add report button
create_report_1

### Form with relevant file entries
create_report_2

### Form with no relevant file entries
create_report_3

    ```
    git rebase -i $(git merge-base HEAD master)
    git push origin NAME_OF_BRANCH --force-with-lease
    ```

### CODE REVIEW

**Comment by MichaelJamesParsons** [comment]
@ELD  This PR depends on #95 being merged.

**Comment by MichaelJamesParsons** [comment]
@ELD ping

**Comment by ELD** [comment]
@MichaelJamesParsons The original PR mentioned needing #93 merged, not #95. Now that both PRs are merged, rebase and I'll review it again tonight.

**Comment by MichaelJamesParsons** [comment]
@ELD I later realized this PR depends on both #93 and #95. Ready for review.

**Comment by MichaelJamesParsons** [comment]
@ELD ping

**Pull request merged**
