### PR TITLE
37 create member file

### PR DESCRIPTION
**Pull request by MichaelJamesParsons**
#### Before you submit this PR for review, make sure the following tasks are complete.

- [x] Added relevant documentation.
- [x] Updated unit tests.
- [x] Made sure all tests are passing with `yarn test`
- [x] Ensured all code meets the [standard JS](https://standardjs.com) style guide.
- [x] Removed debug code.
- [x] Included screenshot if applicable.
- [x] Squashed changes into a single commit.

    ```
    git rebase -i $(git merge-base HEAD master)
    git push origin NAME_OF_BRANCH --force-with-lease
    ```

## Notes
- The UI will not render a snackbar to indicate if the operation is successful. This will be implemented (along with more validation) in a separate PR.
- ACL will be handled through WCF. To be added in a separate PR.

## Screenshots
titan_create_file_entry

### CODE REVIEW

**Comment by ELD** [comment]
So, one kludge that static12 had that I was hoping we could get away from is the variation in "start date" and "end date" for events that logically only happen at a point-in-time.

For instance:
- An A-15 has a date range because they're punished for a certain period of time (i.e. start date and end date)
- A Leave of Absence has a date range because they're gone for a period of time (i.e. start date and end date)
- A promotion is an event that happens at a single point in time (i.e. a singular date, maybe just "Date")

Does that make sense? Would it be possible to implement behavior similar to that? We can punt that to another issue/PR in something like `0.1.5` if need-be.

**Comment by MichaelJamesParsons** [comment]
This can be implemented without a hassle. I'll work on it in the next day or two.

Long term, I'd like to steer away from manually entering member files all together. These files are essentially logging events during a member's time in the community. Instead, we should create interfaces for performing specific actions, such as issuing an A15 or promoting a member. Then have those actions automatically add an entry to the member's history.

Certain file entries, such as NOA's can be processed without human interaction, and will reduce the amount of manual administrative work.

**Comment by MichaelJamesParsons** [comment]
@ELD Ready, but pending #36 to be squashed and merged.

**Comment by MichaelJamesParsons** [comment]
@ELD Ready for review.

Additional changes:
- Added client side validation. Submit button will remain disabled until the appropriate fields have correct values.
- A15 and LOA entry types will render start/end date fields. All other types will render just the one.

**Pull request merged**
