### PR TITLE
Added contribution documents

### PR DESCRIPTION
**Pull request by MichaelJamesParsons**
Added,

- Contribution processes
- Code of conduct
- PR template
- Issue template
- License

### CODE REVIEW

**Comment by ELD** [comment]
Not positive about the MIT licensing, but otherwise looks good. I'll have a chat with some others.

**Comment by MichaelJamesParsons** [comment]
I removed the license.

**Comment by ELD** [comment]
Awesome. Thanks! I’ll approve the PR sometime today. The license is just an issue with allowing the free reuse of the code. We’ll have to have more internal discussion on this at a later date.

**Comment by ELD** [comment]
@MichaelJamesParsons You're going to kill me, but feel free to add the MIT license back.

**Comment by MichaelJamesParsons** [comment]
Are you sure? What changed your mind?

**Pull request merged**
